captain/projects/urls.py
from django.conf.urls import patterns, url

from captain.projects import views


urlpatterns = patterns('',
    url(r'^$', views.AllProjects.as_view(), name='projects.all'),
    url(r'^my_projects/$', views.MyProjects.as_view(), name='projects.mine'),
    url(r'^projects/$', views.AllProjects.as_view(), name='projects.list'),

    url(r'^projects/(?P<project_id>\d+)/$', views.ProjectHistory.as_view(),
        name='projects.details.history'),
    url(r'^projects/(?P<pk>\d+)/run_command$', views.RunCommand.as_view(),
        name='projects.details.run_command'),
    url(r'^projects/(?P<project_id>\d+)/schedule$', views.Schedule.as_view(),
        name='projects.details.schedule'),
    url(r'^projects/(?P<project_id>\d+)/sent_command/(?P<pk>\d+)$',
        views.SentCommandDetails.as_view(), name='projects.details.sent_command'),
)

captain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import jingo.monkey
from commonware.response.cookies.monkeypatch import patch_all as patch_cookies


admin.autodiscover()


urlpatterns = patterns('',
    url(r'', include('captain.projects.urls')),
    url(r'', include('captain.users.urls')),

    (r'^auth/', include('django_browserid.urls')),

    (r'^admin/', include(admin.site.urls)),
)


# In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    ) + staticfiles_urlpatterns()


# Monkeypatches!
# Patch Django to support __html__ for rendering in Jinja.
jingo.monkey.patch()

# Patch HttpResponse to use secure, httponly cookies by default.
patch_cookies()

captain/projects/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.files.base import ContentFile
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import dateformat, timezone

from captain.projects import shove


class Project(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    homepage = models.URLField()

    queue = models.CharField(max_length=255)
    project_name = models.CharField(max_length=255, unique=True)
    shove_instances = models.ManyToManyField('ShoveInstance', related_name='projects')

    class Meta:
        permissions = (
            ('can_run_commands', 'Can run commands'),
        )

    def send_command(self, user, command, shove_instances):
        """
        Send a command to be executed by shove for this project.

        :param user:
            User that is running the command. This can be None if the
            command is being run automatically as a scheduled command.

        :param command:
            Name of the command to execute.

        :param shove_instances:
            List or queryset of ShoveInstances that the command should
            be sent to.

        :raises:
            PermissionDenied: If a user is given and that user does not
            have permission to run a command on this project.
        """
        if user and not user.has_perm('projects.can_run_commands', self):
            raise PermissionDenied('User `{0}` does not have permission to run command `{1}` on '
                                   'project `{2}`.'.format(user.email, command, self.name))

        active_shove_instances = self.shove_instances.filter(active=True)
        if not frozenset(shove_instances).issubset(frozenset(active_shove_instances)):
            raise ValueError('Given shove instances are not in the set of active shove instances '
                             'for this project.')

        sent_command = SentCommand.objects.create(project=self, user=user, command=command)
        for shove_instance in shove_instances:
            shove_instance.send_command(self, sent_command)
        return sent_command

    def get_absolute_url(self):
        return reverse('projects.details.history', args=(self.pk,))

    def __unicode__(self):
        return self.name


class ShoveInstance(models.Model):
    """An instance of shove running on a remote server."""
    routing_key = models.CharField(max_length=255, unique=True, blank=False)
    hostname = models.CharField(max_length=255, blank=False)

    active = models.BooleanField(default=False)
    last_heartbeat = models.DateTimeField(default=None, null=True)

    def send_command(self, project, sent_command):
        """
        Send a command to be executed by this ShoveInstance.

        :param project:
            Project instance for the project to run the given command
            on.

        :param sent_command:
            SentCommand instance to log the results of this command to.
        """
        log = CommandLog.objects.create(shove_instance=self, sent_command=sent_command)
        shove.send_command(self.routing_key, project.project_name, sent_command.command, log.pk)
        return log

    def __unicode__(self):
        return self.hostname


class ScheduledCommand(models.Model):
    """Command that runs automatically at a certain interval."""
    project = models.ForeignKey(Project)
    command = models.CharField(max_length=255)
    user = models.ForeignKey(User)
    hostnames = models.TextField(blank=True)

    INTERVAL_CHOICES = (
        (15, 'Every 15 Minutes'),
        (30, 'Every 30 Minutes'),
        (60, 'Once an hour'),
        (180, 'Once every 3 hours'),
        (360, 'Once every 6 hours'),
        (720, 'Once every 12 hours'),
        (1440, 'Once a day'),
    )
    interval_minutes = models.IntegerField('Interval', choices=INTERVAL_CHOICES, default=15)
    last_run = models.DateTimeField(null=True)

    @property
    def is_due(self):
        """
        True if it has been self.interval_minutes since the last run of
        this command, False otherwise.
        """
        if not self.last_run:
            return True
        else:
            return (timezone.now() - self.last_run) > timedelta(minutes=self.interval_minutes)

    @property
    def shove_instances(self):
        """
        Queryset of ShoveInstances with hostnames matching the ones
        specified for this command.
        """
        return ShoveInstance.objects.filter(active=True, hostname__in=self.hostnames.split(','))

    def run(self):
        """
        Send the command for this scheduled command and log the current
        time as the last run.
        """
        self.project.send_command(None, self.command, self.shove_instances)
        self.last_run = timezone.now()
        self.save()


class SentCommand(models.Model):
    """
    A command that has been sent to a set of Shove instances for a
    particular project.
    """
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User, null=True)
    command = models.CharField(max_length=255)
    sent = models.DateTimeField(auto_now_add=True)

    @property
    def success(self):
        """
        True if all shove instances executed this command successfully,
        None if there are instances that haven't reported back, and
        False if there were failures.
        """
        successes = [log.success for log in self.commandlog_set.all()]
        return None if None in successes else all(successes)

    def get_absolute_url(self):
        return reverse('projects.details.sent_command', args=(self.project.pk, self.pk))


class CommandLog(models.Model):
    """Log of information about a single run of a command."""
    sent_command = models.ForeignKey(SentCommand, null=True)
    shove_instance = models.ForeignKey(ShoveInstance, null=True)
    sent = models.DateTimeField(auto_now_add=True)

    def _logfile_filename(self, filename):
        return 'logs/{project_slug}/{command}.{hostname}.{sent}.log'.format(
            project_slug=self.sent_command.project.slug,
            command=slugify(self.sent_command.command),
            hostname=slugify(self.shove_instance.hostname),
            sent=dateformat.format(self.sent, 'U')
        )
    logfile = models.FileField(blank=True, default='', upload_to=_logfile_filename)
    return_code = models.IntegerField(null=True, default=None)

    @property
    def success(self):
        return None if self.return_code is None else self.return_code == 0

    @property
    def log(self):
        with self.logfile as f:
            return f.read()

    @log.setter
    def log(self, content):
        self.logfile.save(None, ContentFile(content), save=False)

captain/projects/forms.py
from django import forms
from django.core.exceptions import ValidationError

from captain.projects.models import ScheduledCommand, ShoveInstance


class RunCommandForm(forms.Form):
    command = forms.CharField(required=True,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    shove_instances = forms.ModelMultipleChoiceField(
        required=True, queryset=ShoveInstance.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        # Set queryset for shove_instances field to instances from the
        # given project.
        project = kwargs.pop('project')
        super(RunCommandForm, self).__init__(*args, **kwargs)

        self.fields['shove_instances'].queryset = project.shove_instances.filter(active=True)

    def clean_command(self):
        if self.cleaned_data['command'].strip() == '':
            raise ValidationError('Command cannot be blank.')
        return self.cleaned_data['command']


class CreateScheduledCommandForm(forms.ModelForm):
    hostnames = forms.ModelMultipleChoiceField(
        required=True, queryset=ShoveInstance.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        # Set queryset for hostnames field to instances from the
        # given project.
        project = kwargs.pop('project')
        super(CreateScheduledCommandForm, self).__init__(*args, **kwargs)

        self.fields['hostnames'].queryset = project.shove_instances.filter(active=True)

    def clean_hostnames(self):
        """
        Convert list of models to comma-seperated hostnames that the
        model expects.
        """
        shove_instances = self.cleaned_data['hostnames']
        return ','.join([instance.hostname for instance in shove_instances])

    class Meta:
        model = ScheduledCommand
        fields = ('command', 'interval_minutes', 'hostnames')
        widgets = {
            'command': forms.TextInput(attrs={'class': 'form-control'}),
            'interval_minutes': forms.Select(attrs={'class': 'form-control'}),
        }

captain/projects/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import FormView, ListView
from django.views.generic.detail import DetailView, SingleObjectMixin

from guardian.mixins import LoginRequiredMixin
from guardian.shortcuts import get_objects_for_user

from captain.projects.forms import CreateScheduledCommandForm, RunCommandForm
from captain.projects.mixins import PermissionRequiredMixin
from captain.projects.models import Project, SentCommand


class AllProjects(ListView):
    """List all projects registered with Captain."""
    model = Project
    template_name = 'projects/projects.html'


class MyProjects(LoginRequiredMixin, ListView):
    """List projects that the current user has permission to run commands on."""
    template_name = 'projects/my_projects.html'

    def get_queryset(self):
        return get_objects_for_user(self.request.user, 'can_run_commands', Project)


class RunCommand(PermissionRequiredMixin, SingleObjectMixin, FormView):
    """Show and process a form for running commands on a project."""
    model = Project
    permission_required = 'projects.can_run_commands'
    form_class = RunCommandForm
    template_name = 'projects/details/run_command.html'
    context_object_name = 'project'

    def dispatch(self, *args, **kwargs):
        # Workaround for an issue in SingleObjectMixin where it relies on self.object being set
        # before it can run get_context_data.
        self.object = self.get_object()
        return super(RunCommand, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(RunCommand, self).get_form_kwargs()
        kwargs['project'] = self.object
        return kwargs

    def form_valid(self, form):
        """Send the submitted command to shove and redirect to the log list."""
        project = self.get_object()
        project.send_command(self.request.user, form.cleaned_data['command'],
                             form.cleaned_data['shove_instances'])
        messages.success(self.request, 'Command sent successfully!')
        return redirect(project)

    def form_invalid(self, form):
        """Notify the user of the issue and redisplay the command form."""
        messages.error(self.request, 'There was a problem sending your command. Please try again.')
        return super(RunCommand, self).form_invalid(form)

    def permission_denied(self):
        """
        Notify the user that they do not have permission to run commands and redirect to the log
        list.
        """
        messages.error(self.request, 'You do not have permission to run commands for {project}.'
                       .format(project=self.object.name))
        return redirect(reverse('projects.details.history', args=(self.object.pk,)))


class ProjectHistory(ListView):
    """
    Show a list of all the log entries for commands run on a project.
    """
    template_name = 'projects/details/history.html'
    context_object_name = 'sent_commands'
    paginate_by = 25

    def get_queryset(self):
        self.project = get_object_or_404(Project, pk=self.kwargs['project_id'])
        return self.project.sentcommand_set.order_by('-sent')

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectHistory, self).get_context_data(*args, **kwargs)
        context['project'] = self.project
        return context


class SentCommandDetails(DetailView):
    model = SentCommand
    context_object_name = 'sent_command'
    template_name = 'projects/details/sent_command.html'

    def get_queryset(self):
        return SentCommand.objects.filter(project_id=self.kwargs['project_id'])

    def get_context_data(self, *args, **kwargs):
        context = super(SentCommandDetails, self).get_context_data(*args, **kwargs)
        context['project'] = Project.objects.get(id=self.kwargs['project_id'])
        context['logs'] = self.object.commandlog_set.order_by('shove_instance__hostname')
        return context


class Schedule(PermissionRequiredMixin, FormView):
    template_name = 'projects/details/schedule.html'
    form_class = CreateScheduledCommandForm
    permission_required = 'projects.can_run_commands'

    def dispatch(self, *args, **kwargs):
        self.object = self.get_object()
        return super(Schedule, self).dispatch(*args, **kwargs)

    def get_object(self):
        return get_object_or_404(Project, pk=self.kwargs['project_id'])

    def get_context_data(self, *args, **kwargs):
        context = super(Schedule, self).get_context_data(*args, **kwargs)
        context['project'] = self.object
        context['scheduled_commands'] = (self.object.scheduledcommand_set
                                         .order_by('interval_minutes'))
        return context

    def get_form_kwargs(self):
        kwargs = super(Schedule, self).get_form_kwargs()
        kwargs['project'] = self.object
        return kwargs

    def form_valid(self, form):
        """Save the scheduled command and redirect back to the list."""
        command = form.save(commit=False)
        command.project = self.object
        command.user = self.request.user
        command.save()
        return redirect(reverse('projects.details.schedule', args=(self.object.pk,)))

    def form_invalid(self, form):
        """Notify the user of the issue and redisplay the form."""
        messages.error(self.request, 'There was a problem saving your command. Please try again.')
        return super(Schedule, self).form_invalid(form)

    def permission_denied(self):
        """
        Notify the user that they do not have permission to schedule commands and redirect to the
        log list.
        """
        messages.error(self.request, 'You do not have permission to schedule commands for '
                                     '{project}.'.format(project=self.object.name))
        return redirect(reverse('projects.details.history', args=(self.object.pk,)))

captain/projects/templates/projects/details/base.html
{% extends 'base/base.html' %}

{% set page_id = page_id|default(None) %}

{% macro nav_tab(id, link, text) -%}
  <li {% if page_id == id %}class="active"{% endif %}><a href="{{ link }}">{{ text }}</a></li>
{%- endmacro %}

{% block content %}
  <h1>Project: {{ project.name }}</h1>
  <p class="lead"><a href="{{ project.homepage }}">{{ project.homepage }}</a></p>

  <ul class="nav nav-tabs">
    {{ nav_tab('history', url('projects.details.history', project.pk), 'Command History') }}
    {% if user.has_perm('projects.can_run_commands', project) %}
      {{ nav_tab('run_command', url('projects.details.run_command', project.pk), 'Run Command') }}
      {{ nav_tab('schedule', url('projects.details.schedule', project.pk), 'Command Schedule') }}
    {% endif %}
  </ul>

  {% block tab_content %}{% endblock %}
{% endblock %}

captain/projects/templates/projects/details/history.html
{% extends 'projects/details/base.html' %}

{% from 'base/pagination.html' import pagination %}

{% set page_id = 'history' %}

{% block tab_content %}
  <h2>Command History</h2>
    <table class="table table-striped">
      <tr>
        <th>User</th>
        <th>Command</th>
        <th>Date</th>
        <th>Result</th>
        <th></th>
      </tr>
      {% for sent_command in sent_commands %}
        <tr {% if not sent_command.success is none -%}
              class="{{ 'success' if sent_command.success else 'danger' }}"
            {%- endif %}>
          <td>{{ user_display(sent_command.user) }}</td>
          <td>{{ sent_command.command }}</td>
          <td>{{ sent_command.sent.strftime('%b %d, %Y %H:%M:%S %Z') }}</td>
          <td>
            {% if sent_command.success is none %}
              Pending
            {% elif sent_command.success %}
              Success
            {% else %}
              Failed
            {% endif %}
          </td>
          <td>
            <a href="{{ sent_command.get_absolute_url() }}">More Info</a>
          </td>
        </tr>
      {% else %}
        <td colspan="3">No commands have been run for this project yet.</td>
      {% endfor %}
    </table>

    {{ pagination(page_obj) }}
{% endblock %}

captain/projects/templates/projects/details/run_command.html
{% extends 'projects/details/base.html' %}

{% from 'base/forms.html' import form_field %}

{% set page_id = 'run_command' %}

{% block tab_content %}
  <div class="run-command-panel panel panel-primary">
    <div class="panel-heading"><h2 class="panel-title">Send a command. For a list of valid commands, see your project's <em>commands.procfile.</em></h2></div>
    <div class="panel-body">
      <form method="post" action="{{ url('projects.details.run_command', project.pk) }}">
        {{ csrf() }}
        {{ form_field(form.command) }}
        {{ form_field(form.shove_instances) }}
        <button type="submit" class="btn btn-primary">Send</button>
      </form>
    </div>
  </div>
{% endblock %}

captain/projects/templates/projects/details/schedule.html
{% extends 'projects/details/base.html' %}

{% from 'base/forms.html' import form_field %}

{% set page_id = 'schedule' %}

{% block tab_content %}
  <h2>Automatic Command Schedule</h2>
    <table class="table table-striped">
      <tr>
        <th>Command</th>
        <th>Created By</th>
        <th>Interval</th>
        <th>Last Run</th>
        <th>Hostnames</th>
      </tr>
      {% for command in scheduled_commands %}
        <tr>
          <td>{{ command.command }}</td>
          <td>{{ user_display(command.user) }}</td>
          <td>{{ command.get_interval_minutes_display() }}</td>
          <td>
            {% if command.last_run %}
              {{ command.last_run.strftime('%b %d, %Y %H:%M:%S %Z') }}
            {% else %}
              Never
            {% endif %}
          </td>
          <td>
            <select multiple rows="3">
              {% for hostname in command.hostnames.split(',') %}
                <option>{{ hostname }}</option>
              {% endfor %}
            </select>
          </td>
        </tr>
      {% else %}
        <td colspan="5">No commands have been scheduled for this project yet.</td>
      {% endfor %}
    </table>

    <div class="panel panel-primary">
      <div class="panel-heading"><h2 class="panel-title">Add New Command to Schedule</h2></div>
      <div class="panel-body">
        <form method="post">
          {{ csrf() }}
          {{ form_field(form.command) }}
          {{ form_field(form.interval_minutes) }}
          {{ form_field(form.hostnames) }}
          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
{% endblock %}

captain/projects/templates/projects/details/sent_command.html
{% extends 'projects/details/base.html' %}

{% set page_id = 'history' %}

{% block site_js %}
  {{ super() }}
  <script src="{{ static('js/sent_command.js') }}"></script>
{% endblock %}

{% block tab_content %}
  <h2>Command Details</h2>

  <dl class="dl-horizontal">
    <dt>Sent by</dt>
    <dd>{{ user_display(sent_command.user) }}</dd>

    <dt>Command</dt>
    <dd><code>{{ sent_command.command }}</code></dd>

    <dt>Date</dt>
    <dd>{{ sent_command.sent.strftime('%b %d, %Y %H:%M:%S %Z') }}</dd>

    <dt>Result</dt>
    <dd>
      {% if sent_command.success is none %}
        <span class="label label-default">Pending</span>
      {% elif sent_command.success %}
        <span class="label label-success">Success</span>
      {% else %}
        <span class="label label-danger">Error</span>
      {% endif %}
    </dd>
  </dl>

  <h3>Individual Logs</h3>
  <div class="panel-group" id="shove-logs">
    {% for log in logs %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#shove-logs" href="#log-{{ log.pk }}">
              {{ log.shove_instance.hostname }}
            </a>
          </h4>
        </div>
        {% if log.logfile %}
          <div id="log-{{ log.pk }}" class="panel-collapse collapse not-loaded" data-log-url="{{ log.logfile.url }}">
            <div class="panel-body">
              <pre class="log-content">Loading log...</pre>
            </div>
          </div>
        {% else %}
          <div id="log-{{ log.pk }}" class="panel-collapse collapse">
            <div class="panel-body">
              <p>No log available.</p>
            </div>
          </div>
        {% endif %}
      </div>
    {% else %}
      <div class="panel panel-default">
        <div class="panel-body">
          <p>No logs found for this command.</p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}